# Generated by Django 4.1.7 on 2023-02-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_conductor', models.CharField(max_length=255)),
                ('precio_viaje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_viaje', models.CharField(max_length=255)),
            ],
        ),
    ]
